#!/usr/bin/env python3

import sys
import flask
import json
import psycopg2

app = flask.Flask(__name__)

# database = 'yourdatabasename'
# user = 'yourusername'
# password = 'yourdatabasepassword'

# try:
#     connection = psycopg2.connect(database='butterfieldp@perlman.mathcs.carleton.edu', user='user', password='guest')
# except Exception as e:
#     print(e)
#     exit()

# Query the database, leaving you with a "cursor"--an object you can
# use to iterate over the rows generated by your query.
# try:
#     cursor = connection.cursor()
#     query = 'SELECT first_name, last_name FROM authors ORDER BY last_name'
#     cursor.execute(query)
# except Exception as e:
#     print(e)
#     exit()

@app.route('/')
def hello():
    return 'Hello World'
#
# @app.route('/actor/<last_name>')
# def get_actor(last_name):
#     ''' Returns the first matching actor, or an empty dictionary if there's no match. '''
#     actor_dictionary = {}
#     lower_last_name = last_name.lower()
#     for actor in actors:
#         if actor['last_name'].lower().startswith(lower_last_name):
#             actor_dictionary = actor
#             break
#     return json.dumps(actor_dictionary)

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print('Usage: {0} host port'.format(sys.argv[0]))
        print('  Example: {0} perlman.mathcs.carleton.edu 5101'.format(sys.argv[0]))
        exit()

    host = sys.argv[1]
    port = int(sys.argv[2])
    app.run(host=host, port=port, debug=True)
